"""
Icons for the custom capabilities.

Without an `icon` a custom capability renders on the device tile as a dashed placeholder square,
which is what "Prey detected", "Human activity", "Last event", "Last refusal" and each cat looked
like. The official capabilities beside them (`alarm_motion`, `alarm_connectivity`) ship their own
glyphs, so the tile read as half-finished.

Filled silhouettes, not line art: that is what Homey's own capability glyphs are, and at ~28px a
stroked outline turns to mush. (The *app* icon is the opposite — see dev/make-device-icon.py.)

Everything is built from four primitives so the same definitions can be both written as SVG and
rasterised into a contact sheet. There is no SVG renderer on this machine, and shipping icons
nobody has looked at is exactly how the last two rounds of asset mistakes happened.

    python3 dev/make-capability-icons.py /tmp/sheet.png
"""

import math
import os
import struct
import sys
import zlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = f'{ROOT}/assets/capabilities'
BOX = 32


# --- primitives -------------------------------------------------------------------------------

def circle(cx, cy, r):
    return ('circle', (cx, cy, r))


def rrect(x, y, w, h, rad):
    return ('rrect', (x, y, w, h, rad))


def poly(points):
    return ('poly', (points,))


def stroke(points, width):
    return ('stroke', (points, width))


def ring(cx, cy, r, width):
    return ('ring', (cx, cy, r, width))


ICONS = {
    # A mouse: haunch, head, ear, tail. The tail is what makes it read as prey and not a blob.
    'alarm_prey_ONLYCAT': [
        circle(13, 19, 7.2),
        circle(21.5, 17, 5.0),
        circle(23.5, 11.5, 3.1),
        stroke([(6.5, 21), (3.2, 18), (5.2, 13.5)], 2.2),
    ],
    # A person, deliberately unlike the official motion glyph next to it: standing, not walking.
    'alarm_human_ONLYCAT': [
        circle(16, 7, 3.9),
        rrect(13.2, 11.6, 5.6, 11, 2.8),
        stroke([(13.4, 14.5), (8.8, 18.6)], 2.6),
        stroke([(18.6, 14.5), (23.2, 18.6)], 2.6),
        stroke([(14.6, 21.6), (12.4, 28.6)], 2.6),
        stroke([(17.4, 21.6), (19.6, 28.6)], 2.6),
    ],
    # A paw print: something happened at the flap, and a cat did it.
    'last_event_ONLYCAT': [
        circle(16, 21.5, 6.6),
        circle(8.6, 14.2, 3.0),
        circle(13.4, 10.4, 3.2),
        circle(18.6, 10.4, 3.2),
        circle(23.4, 14.2, 3.0),
    ],
    # A barred circle: refused. Reads at a glance and needs no colour.
    'last_blocked_ONLYCAT': [
        ring(16, 16, 11, 3.0),
        stroke([(9.2, 9.2), (22.8, 22.8)], 3.0),
    ],
    # A cat's face for the per-cat sensors — the one glyph that repeats down the tile.
    'cat_home_ONLYCAT': [
        poly([(8.0, 14.5), (8.4, 4.5), (15.2, 9.6)]),
        poly([(24.0, 14.5), (23.6, 4.5), (16.8, 9.6)]),
        circle(16, 18.5, 9.2),
    ],
    # The door policy: a short list of rules.
    'policy_ONLYCAT': [
        rrect(5.5, 3.5, 21, 25, 3.5),
        rrect(9.5, 9.0, 13, 2.2, 1.1),
        rrect(9.5, 14.9, 13, 2.2, 1.1),
        rrect(9.5, 20.8, 8.5, 2.2, 1.1),
    ],
}

# `policy_ONLYCAT` draws the page as a filled card with cut-out lines, so the lines must be
# knocked out rather than drawn on top. Recorded here rather than guessed from shape order.
KNOCKOUT = {'policy_ONLYCAT': 1}


# --- SVG --------------------------------------------------------------------------------------

def to_svg(name, shapes) -> str:
    knock = KNOCKOUT.get(name)
    body = []
    for i, (kind, args) in enumerate(shapes):
        fill = '#ffffff' if (knock is not None and i >= knock) else '#111918'
        if kind == 'circle':
            cx, cy, r = args
            body.append(f'  <circle cx="{cx}" cy="{cy}" r="{r}" fill="{fill}"/>')
        elif kind == 'rrect':
            x, y, w, h, rad = args
            body.append(f'  <rect x="{x}" y="{y}" width="{w}" height="{h}" '
                        f'rx="{rad}" ry="{rad}" fill="{fill}"/>')
        elif kind == 'poly':
            pts = ' '.join(f'{x},{y}' for x, y in args[0])
            body.append(f'  <polygon points="{pts}" fill="{fill}"/>')
        elif kind == 'stroke':
            pts, width = args
            d = ' '.join(f'{x},{y}' for x, y in pts)
            body.append(f'  <polyline points="{d}" fill="none" stroke="{fill}" '
                        f'stroke-width="{width}" stroke-linecap="round" stroke-linejoin="round"/>')
        elif kind == 'ring':
            cx, cy, r, width = args
            body.append(f'  <circle cx="{cx}" cy="{cy}" r="{r}" fill="none" '
                        f'stroke="{fill}" stroke-width="{width}"/>')
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f'<!-- {name} — generated by dev/make-capability-icons.py -->\n'
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {BOX} {BOX}" '
        f'width="{BOX}" height="{BOX}">\n' + '\n'.join(body) + '\n</svg>\n'
    )


# --- preview ----------------------------------------------------------------------------------

def rrect_distance(px, py, x, y, w, h, rad):
    cx, cy = x + w / 2, y + h / 2
    dx = abs(px - cx) - (w / 2 - rad)
    dy = abs(py - cy) - (h / 2 - rad)
    return math.hypot(max(dx, 0.0), max(dy, 0.0)) + min(max(dx, dy), 0.0) - rad


def seg_distance(px, py, x1, y1, x2, y2):
    dx, dy = x2 - x1, y2 - y1
    n = dx * dx + dy * dy
    t = 0.0 if n == 0 else max(0.0, min(1.0, ((px - x1) * dx + (py - y1) * dy) / n))
    return math.hypot(px - (x1 + t * dx), py - (y1 + t * dy))


def in_poly(px, py, pts):
    inside = False
    for i in range(len(pts)):
        x1, y1 = pts[i]
        x2, y2 = pts[(i + 1) % len(pts)]
        if (y1 > py) != (y2 > py) and px < x1 + (py - y1) * (x2 - x1) / (y2 - y1):
            inside = not inside
    return inside


def hits(px, py, kind, args):
    if kind == 'circle':
        cx, cy, r = args
        return math.hypot(px - cx, py - cy) <= r
    if kind == 'rrect':
        return rrect_distance(px, py, *args) <= 0
    if kind == 'poly':
        return in_poly(px, py, args[0])
    if kind == 'stroke':
        pts, width = args
        return any(seg_distance(px, py, *pts[i], *pts[i + 1]) <= width / 2
                   for i in range(len(pts) - 1))
    if kind == 'ring':
        cx, cy, r, width = args
        return abs(math.hypot(px - cx, py - cy) - r) <= width / 2
    return False


def sheet(path, cell=96, ss=3):
    names = list(ICONS)
    w, h = cell * len(names), cell
    scale = BOX / cell
    step, weight = 1.0 / ss, 1.0 / (ss * ss)

    rows = bytearray()
    for y in range(h):
        rows.append(0)
        for x in range(w):
            name = names[x // cell]
            shapes = ICONS[name]
            knock = KNOCKOUT.get(name)
            ink = 0.0
            for sy in range(ss):
                for sx in range(ss):
                    px = ((x % cell) + (sx + 0.5) * step) * scale
                    py = (y + (sy + 0.5) * step) * scale
                    on = False
                    for i, (kind, args) in enumerate(shapes):
                        if hits(px, py, kind, args):
                            on = not (knock is not None and i >= knock)
                    if on:
                        ink += weight
            v = round(255 * (1 - ink))
            rows += bytes((v, v, v, 255))

    def chunk(tag, data):
        return (struct.pack('>I', len(data)) + tag + data
                + struct.pack('>I', zlib.crc32(tag + data) & 0xffffffff))

    out = b'\x89PNG\r\n\x1a\n'
    out += chunk(b'IHDR', struct.pack('>IIBBBBB', w, h, 8, 6, 0, 0, 0))
    out += chunk(b'IDAT', zlib.compress(bytes(rows), 9))
    out += chunk(b'IEND', b'')
    open(path, 'wb').write(out)


os.makedirs(OUT, exist_ok=True)
for name, shapes in ICONS.items():
    open(f'{OUT}/{name}.svg', 'w').write(to_svg(name, shapes))
    print(f'wrote {OUT}/{name}.svg')

if len(sys.argv) > 1:
    sheet(sys.argv[1])
    print(f'contact sheet ({", ".join(ICONS)}) -> {sys.argv[1]}')
